// ============================================================
//  ZAX Marketplace — Catálogo de Produtos
// ============================================================

const PRODUCTS_DATA = [
    // ── ELETRÔNICOS ──
    {
        id: 1,
        name: 'Fone Bluetooth Pro Max',
        description: 'Som Hi-Fi com cancelamento de ruído ativo. Bateria de 40h. Conexão multipontos.',
        price: 189.90,
        originalPrice: 299.90,
        category: 'eletronicos',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop&q=80',
        rating: 4.8,
        reviewCount: 342,
        sold: 1289,
        featured: true,
        badge: 'Mais Vendido',
        tags: ['bluetooth', 'wireless', 'noise-cancelling'],
    },
    {
        id: 2,
        name: 'Smartwatch Fitness Ultra',
        description: 'Monitor cardíaco, GPS integrado, tela AMOLED 1.9". Resistente à água IP68.',
        price: 249.90,
        originalPrice: 399.90,
        category: 'eletronicos',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop&q=80',
        rating: 4.6,
        reviewCount: 218,
        sold: 856,
        featured: true,
        badge: 'Lançamento',
        tags: ['smartwatch', 'fitness', 'gps'],
    },
    {
        id: 3,
        name: 'Caixa de Som Portátil 30W',
        description: 'Bluetooth 5.3, à prova d\'água IPX7, bateria de 24h. Graves profundos.',
        price: 159.90,
        originalPrice: 229.90,
        category: 'eletronicos',
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=300&fit=crop&q=80',
        rating: 4.7,
        reviewCount: 567,
        sold: 2341,
        featured: false,
        badge: null,
        tags: ['speaker', 'bluetooth', 'waterproof'],
    },
    {
        id: 4,
        name: 'Carregador Wireless MagSafe',
        description: 'Carregamento rápido 15W, compatível com iPhone e Android. Design ultra fino.',
        price: 89.90,
        originalPrice: 149.90,
        category: 'eletronicos',
        image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&q=80',
        rating: 4.5,
        reviewCount: 189,
        sold: 945,
        featured: false,
        badge: null,
        tags: ['charger', 'wireless', 'magsafe'],
    },
    {
        id: 5,
        name: 'Webcam 4K AutoFocus',
        description: 'Resolução 4K, microfone duplo com redução de ruído. Ideal para streams e calls.',
        price: 199.90,
        originalPrice: 329.90,
        category: 'eletronicos',
        image: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=300&fit=crop&q=80',
        rating: 4.4,
        reviewCount: 132,
        sold: 678,
        featured: false,
        badge: '-39%',
        tags: ['webcam', '4k', 'streaming'],
    },

    // ── MODA ──
    {
        id: 6,
        name: 'Tênis Runner Elite',
        description: 'Sola em gel com amortecimento. Upper em mesh respirável. Conforto o dia todo.',
        price: 219.90,
        originalPrice: 349.90,
        category: 'moda',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop&q=80',
        rating: 4.9,
        reviewCount: 891,
        sold: 4523,
        featured: true,
        badge: 'Top 1',
        tags: ['tenis', 'running', 'esporte'],
    },
    {
        id: 7,
        name: 'Jaqueta Corta-Vento Tech',
        description: 'Tecido impermeável e respirável. Capuz ajustável, bolsos com zíper YKK.',
        price: 179.90,
        originalPrice: 289.90,
        category: 'moda',
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=300&fit=crop&q=80',
        rating: 4.7,
        reviewCount: 345,
        sold: 1567,
        featured: true,
        badge: 'Tendência',
        tags: ['jaqueta', 'impermeavel', 'outdoor'],
    },
    {
        id: 8,
        name: 'Óculos de Sol Polarizado UV400',
        description: 'Lentes polarizadas com proteção UV400. Armação em TR90 ultra leve.',
        price: 89.90,
        originalPrice: 159.90,
        category: 'moda',
        image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop&q=80',
        rating: 4.6,
        reviewCount: 234,
        sold: 1890,
        featured: false,
        badge: null,
        tags: ['oculos', 'polarizado', 'uv400'],
    },
    {
        id: 9,
        name: 'Mochila Urban Notebook 15"',
        description: 'Compartimento acolchoado para notebook. Anti-furto, porta USB. 25L.',
        price: 149.90,
        originalPrice: 229.90,
        category: 'moda',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop&q=80',
        rating: 4.8,
        reviewCount: 456,
        sold: 2134,
        featured: false,
        badge: 'Popular',
        tags: ['mochila', 'notebook', 'anti-furto'],
    },
    {
        id: 10,
        name: 'Camiseta Dry-Fit Premium',
        description: 'Tecido que seca 3x mais rápido. Proteção solar UPF50+. Corte regular.',
        price: 59.90,
        originalPrice: 99.90,
        category: 'moda',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop&q=80',
        rating: 4.5,
        reviewCount: 678,
        sold: 5678,
        featured: false,
        badge: null,
        tags: ['camiseta', 'dry-fit', 'esporte'],
    },

    // ── CASA ──
    {
        id: 11,
        name: 'Luminária LED Inteligente RGB',
        description: 'Controle por app e voz (Alexa/Google). 16 milhões de cores. Timer e cenas.',
        price: 129.90,
        originalPrice: 199.90,
        category: 'casa',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&h=300&fit=crop&q=80',
        rating: 4.7,
        reviewCount: 312,
        sold: 1456,
        featured: true,
        badge: 'Smart Home',
        tags: ['luminaria', 'led', 'smart'],
    },
    {
        id: 12,
        name: 'Organizador de Mesa Premium',
        description: 'Bambu natural sustentável. 6 compartimentos. Suporte para celular e tablet.',
        price: 79.90,
        originalPrice: 129.90,
        category: 'casa',
        image: 'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=400&h=300&fit=crop&q=80',
        rating: 4.8,
        reviewCount: 189,
        sold: 934,
        featured: false,
        badge: 'Eco',
        tags: ['organizador', 'bambu', 'escritorio'],
    },
    {
        id: 13,
        name: 'Difusor de Aroma Ultrassônico',
        description: 'Capacidade 500ml, LED 7 cores, timer automático. Silencioso < 30dB.',
        price: 99.90,
        originalPrice: 169.90,
        category: 'casa',
        image: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=400&h=300&fit=crop&q=80',
        rating: 4.6,
        reviewCount: 267,
        sold: 1123,
        featured: false,
        badge: null,
        tags: ['difusor', 'aroma', 'relaxamento'],
    },
    {
        id: 14,
        name: 'Kit Vasos Decorativos Minimalistas',
        description: 'Set com 3 vasos em cerâmica mate. Design escandinavo. Cores neutras.',
        price: 119.90,
        originalPrice: 189.90,
        category: 'casa',
        image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&h=300&fit=crop&q=80',
        rating: 4.9,
        reviewCount: 145,
        sold: 789,
        featured: false,
        badge: 'Design',
        tags: ['vaso', 'decoracao', 'ceramica'],
    },
    {
        id: 15,
        name: 'Garrafa Térmica Inox 1L',
        description: 'Mantém quente 24h e gelado 48h. Aço inox 18/8 premium. Livre de BPA.',
        price: 69.90,
        originalPrice: 119.90,
        category: 'casa',
        image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=300&fit=crop&q=80',
        rating: 4.7,
        reviewCount: 534,
        sold: 3456,
        featured: false,
        badge: null,
        tags: ['garrafa', 'termica', 'inox'],
    },

    // ── ACESSÓRIOS ──
    {
        id: 16,
        name: 'Carteira Slim RFID Block',
        description: 'Couro legítimo italiano. Bloqueio RFID, 8 slots para cartões. Ultra fina.',
        price: 99.90,
        originalPrice: 179.90,
        category: 'acessorios',
        image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=300&fit=crop&q=80',
        rating: 4.8,
        reviewCount: 298,
        sold: 1678,
        featured: true,
        badge: 'Premium',
        tags: ['carteira', 'couro', 'rfid'],
    },
    {
        id: 17,
        name: 'Relógio Analógico Classic',
        description: 'Movimento japonês Miyota. Pulseira de couro genuíno. Vidro safira.',
        price: 299.90,
        originalPrice: 499.90,
        category: 'acessorios',
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=300&fit=crop&q=80',
        rating: 4.9,
        reviewCount: 167,
        sold: 567,
        featured: false,
        badge: 'Luxo',
        tags: ['relogio', 'analogico', 'couro'],
    },
    {
        id: 18,
        name: 'Pulseira Magnética Aço Titânio',
        description: 'Aço titânio hipoalergênico. Fecho magnético ajustável. Unissex.',
        price: 69.90,
        originalPrice: 119.90,
        category: 'acessorios',
        image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&h=300&fit=crop&q=80',
        rating: 4.5,
        reviewCount: 213,
        sold: 1234,
        featured: false,
        badge: null,
        tags: ['pulseira', 'titanio', 'magnetica'],
    },
    {
        id: 19,
        name: 'Chaveiro Multifuncional EDC',
        description: '12 funções em 1: abridor, chave hex, régua, cortador. Aço inoxidável.',
        price: 39.90,
        originalPrice: 69.90,
        category: 'acessorios',
        image: 'https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?w=400&h=300&fit=crop&q=80',
        rating: 4.6,
        reviewCount: 456,
        sold: 3456,
        featured: false,
        badge: '-42%',
        tags: ['chaveiro', 'edc', 'multifuncional'],
    },
    {
        id: 20,
        name: 'Necessaire Viagem Organizadora',
        description: 'Compartimentos para cosméticos. Impermeável, ganchos para pendurar.',
        price: 49.90,
        originalPrice: 89.90,
        category: 'acessorios',
        image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=300&fit=crop&q=80',
        rating: 4.7,
        reviewCount: 345,
        sold: 2345,
        featured: false,
        badge: null,
        tags: ['necessaire', 'viagem', 'organizador'],
    },
    {
        id: 21,
        name: 'Ring Light 26cm com Tripé',
        description: 'LED regulável 3 tons de luz. Tripé 2.1m. Suporte celular 360°.',
        price: 109.90,
        originalPrice: 179.90,
        category: 'eletronicos',
        image: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=400&h=300&fit=crop&q=80',
        rating: 4.5,
        reviewCount: 234,
        sold: 1567,
        featured: false,
        badge: null,
        tags: ['ring-light', 'fotografia', 'tripe'],
    },
    {
        id: 22,
        name: 'Boné Snapback Premium',
        description: 'Aba reta bordado 3D. Tecido twill respirável. Ajuste snapback.',
        price: 69.90,
        originalPrice: 99.90,
        category: 'moda',
        image: 'https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=400&h=300&fit=crop&q=80',
        rating: 4.4,
        reviewCount: 189,
        sold: 1234,
        featured: false,
        badge: null,
        tags: ['bone', 'snapback', 'streetwear'],
    },
    {
        id: 23,
        name: 'Tapete Yoga Premium 6mm',
        description: 'TPE ecológico antiderrapante. Dupla camada. Inclui bolsa de transporte.',
        price: 89.90,
        originalPrice: 149.90,
        category: 'casa',
        image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=300&fit=crop&q=80',
        rating: 4.8,
        reviewCount: 312,
        sold: 1890,
        featured: false,
        badge: 'Eco',
        tags: ['yoga', 'tapete', 'fitness'],
    },
    {
        id: 24,
        name: 'Kit Skincare Glow 3 Passos',
        description: 'Sérum vitamina C + hidratante hialurônico + protetor solar FPS50.',
        price: 139.90,
        originalPrice: 219.90,
        category: 'acessorios',
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=300&fit=crop&q=80',
        rating: 4.9,
        reviewCount: 567,
        sold: 4567,
        featured: true,
        badge: 'Best Seller',
        tags: ['skincare', 'vitamina-c', 'protetor-solar'],
    },
];

// ── Reviews de exemplo ──
const SAMPLE_REVIEWS = [
    { productId: 1, user: 'Maria S.', rating: 5, text: 'Qualidade incrível do som! Cancelamento de ruído perfeito. Recomendo demais!', date: '2026-05-20', verified: true, helpful: 45 },
    { productId: 1, user: 'João P.', rating: 4, text: 'Muito bom, bateria dura bastante. Só achei um pouco apertado na cabeça.', date: '2026-05-15', verified: true, helpful: 23 },
    { productId: 1, user: 'Ana L.', rating: 5, text: 'Melhor fone que já tive nessa faixa de preço. Conexão estável e som top.', date: '2026-05-10', verified: true, helpful: 67 },
    { productId: 6, user: 'Carlos M.', rating: 5, text: 'Super confortável! Usei pra correr 10km e zero desconforto. Amortecimento perfeito.', date: '2026-06-01', verified: true, helpful: 89 },
    { productId: 6, user: 'Fernanda R.', rating: 5, text: 'Lindo e funcional. Comprei o preto e já quero outra cor!', date: '2026-05-28', verified: true, helpful: 34 },
    { productId: 6, user: 'Lucas G.', rating: 4, text: 'Ótimo tênis, cabe certinho. Poderia ter mais opções de cor.', date: '2026-05-25', verified: false, helpful: 12 },
    { productId: 11, user: 'Patricia F.', rating: 5, text: 'Transformou meu quarto! As cores são lindas e o app funciona perfeitamente.', date: '2026-05-30', verified: true, helpful: 56 },
    { productId: 16, user: 'Ricardo B.', rating: 5, text: 'Couro de qualidade excepcional. Muito fina, cabe perfeitamente no bolso.', date: '2026-06-02', verified: true, helpful: 78 },
    { productId: 24, user: 'Isabela C.', rating: 5, text: 'Minha pele nunca esteve tão bonita! O sérum é sensacional. Super recomendo!', date: '2026-06-05', verified: true, helpful: 123 },
    { productId: 24, user: 'Camila T.', rating: 4, text: 'Gostei muito, mas o protetor poderia ter mais ml. Fora isso, perfeito!', date: '2026-06-03', verified: true, helpful: 45 },
    { productId: 2, user: 'Roberto D.', rating: 5, text: 'Tela linda, GPS preciso, bateria dura 5 dias. Melhor custo-benefício!', date: '2026-05-22', verified: true, helpful: 90 },
    { productId: 7, user: 'Amanda K.', rating: 5, text: 'Testei na chuva e não passou nada! Material de alta qualidade.', date: '2026-05-18', verified: true, helpful: 67 },
];
